return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "php",
      "php_only",
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "yaml",
      "eex",
      "elixir",
      "erlang",
      "heex",
      "surface",
    },
  },
}
